// public/react-app/src/components/views/default/default.js
import React, { useState } from 'react';
import Tabs from '../../molecules/tabs/tabs';
import List from '../../organisms/list/list';
import './default.css';

export default function DefaultView() {
    const tabs = ['list', 'form'];
    const [activeTab, setActiveTab] = useState(tabs[0]);

    return (
        <div className="default-template">
            <Tabs tabNames={tabs} onTabChange={(val) => setActiveTab(tabs[val])} />
            { activeTab === 'list' && <List /> }
        </div>
    );
}

// public/svelte-app/src/components/views/default.svelte
<script>
    import Tabs from "../molecules/tabs.svelte";
    import List from "../organisms/list.svelte";

    let tabs = ['list', 'form'];
    let activeTab = tabs[0];

    function tabChanged(e) {
        activeTab = tabs[e.detail];
    }
</script>

<div class="default-template">
    <Tabs tabNames={tabs} on:tabChange={tabChanged} />
    {#if activeTab === 'list'}
        <List />
    {/if}
</div>

<style>
    .default-template {
        padding: 20px 10px;
        box-sizing: border-box;
        height: 100%;
        flex: 4;
    }
</style>
