// public/svelte-app/src/components/views/default.svelte
<script>
    import Tabs from "../molecules/tabs.svelte";
    import List from "../organisms/list.svelte";

    let tabs = ['list', 'form'];
    let activeTab = tabs[0];

    function tabChanged(e) {
        activeTab = tabs[e.detail];
    }
</script>

<div class="default-template">
    <Tabs tabNames={tabs} on:tabChange={tabChanged} />
    {#if activeTab === 'list'}
        <List />
    {/if}
</div>

<style>
    .default-template {
        padding: 20px 10px;
        box-sizing: border-box;
        height: 100%;
        flex: 4;
    }
</style>

// public/vue-app/src/components/views/default.vue
<template>
  <div class="default-template">
    <Tabs :tabNames="tabs" @tabChange={tabChange} />
    <List v-if="activeTab === 'list'" />
  </div>
</template>

<script>
import { reactive, toRefs} from 'vue';

import Tabs from '../molecules/tabs.vue';
import List from '../organisms/list.vue';

export default {
  components: {
    Tabs,
    List
  },
  setup() {
    const state = reactive({
      tabs: ['list', 'form'],
      activeTab: 'list'
    });

    function tabChange(tabNumber) {
      state.activeTab = this.state.tabs[tabNumber];
    }

    return { tabChange, ...toRefs(state) }
  }
}
</script>

<style scoped>
  .default-template {
    padding: 20px 10px;
    box-sizing: border-box;
    height: 100%;
    flex: 4;
  }
</style>
